class  validateBubblesort:

    def bubblesortanalist(self):
        print(f'La funcion BubbleSort se categoriza como O(n^2)')

    # def validate_empty_list(self): #O(1)
        # if self.new_list.head is None: -- O(1)
            # raise emptyTypeError() --O(1)
    
        
    # def bubble_sort_linkedlist(self): --O(n^2)
        # try: #o(1)
            # self.validate_empty_list() --O(1)
            # currentNode = self.head --O(1)
            # while currentNode is not None: --O(n)
                # self.validate_number(currentNode.data) --O(1)
            #     # currentNode = currentNode.next --O(1)
            # swapped = True--O(1)
            # i=0   --O(1)
            # c=0     --O(1)
            # while swapped: --O(n)
                # swapped = False --O(1)
                # previousNode = None--O(1)
                # currentNode = self.head--O(1)
                # # while currentNode.next is not None: --O(n^2)
                #     if int(currentNode.data) > int(currentNode.next.data):--O(1)
                #         auxNode = currentNode--O(1)
                #         currentNode = currentNode.next--O(1)
                #         auxNode.next = currentNode.next--O(1)
                #         currentNode.next = auxNode--O(1)
                #         if previousNode is None:--O(1)
                #             self.head = currentNode--O(1)
                #         else:--O(1)
                #             previousNode.next = currentNode--O(1)
                #         swapped = True--O(1)
                #         c+=1--O(1)
                #     previousNode = currentNode--O(1)
                #     currentNode = currentNode.next  --O(1)
                # i+=1--O(1)
            # self.new_list.head = self.head --O(1)
            # self.new_list.print_structre() --O(1)
            # print(f'Cantidad de Iteraciones:{i}') --O(1)
            # print(f'Cantidad de cambios realizados: {c}') --O(1)
        # except (emptyTypeError, ValueError) as error:--O(1)
            # print(f'Existe un error al ordenar la lista {error}') --O(1)